export default function Float() {
    return (
        <div id="wd-float-divs">
            <h2>Float</h2>
            <div>
                <img className="wd-float-right"
                    src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg" />
                Donec id vehicula libero, sed blandit dui. Pellentesque ex massa, suscipit vitae turpis quis, scelerisque elementum felis. Ut venenatis velit eu ipsum suscipit, nec vestibulum elit tempor. Vestibulum ut cursus sem. Sed molestie nunc eu lobortis eleifend. Mauris dignissim mi sed diam mollis, ac facilisis turpis aliquet. Sed eu orci risus. Suspendisse suscipit arcu mauris, ut iaculis tellus dictum et. Morbi eu aliquet leo, quis scelerisque eros. Proin tristique mi velit, ac lacinia diam pharetra in. Mauris ac enim varius, pellentesque diam et, pharetra ante. Donec felis felis, ultricies id ante eu, finibus lobortis ligula. Ut eget porta justo. Fusce venenatis, mi eget maximus interdum, turpis tellus lacinia nulla, et efficitur ipsum quam et sapien. Vivamus eu luctus augue.
                <img className="wd-float-left"
                    src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg" />
                Donec id vehicula libero, sed blandit dui. Pellentesque ex massa, suscipit vitae turpis quis, scelerisque elementum felis. Ut venenatis velit eu ipsum suscipit, nec vestibulum elit tempor. Vestibulum ut cursus sem. Sed molestie nunc eu lobortis eleifend. Mauris dignissim mi sed diam mollis, ac facilisis turpis aliquet. Sed eu orci risus. Suspendisse suscipit arcu mauris, ut iaculis tellus dictum et. Morbi eu aliquet leo, quis scelerisque eros. Proin tristique mi velit, ac lacinia diam pharetra in. Mauris ac enim varius, pellentesque diam et, pharetra ante. Donec felis felis, ultricies id ante eu, finibus lobortis ligula. Ut eget porta justo. Fusce venenatis, mi eget maximus interdum, turpis tellus lacinia nulla, et efficitur ipsum quam et sapien. Vivamus eu luctus augue.
                <img className="wd-float-right"
                    src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg" />
                Donec id vehicula libero, sed blandit dui. Pellentesque ex massa, suscipit vitae turpis quis, scelerisque elementum felis. Ut venenatis velit eu ipsum suscipit, nec vestibulum elit tempor. Vestibulum ut cursus sem. Sed molestie nunc eu lobortis eleifend. Mauris dignissim mi sed diam mollis, ac facilisis turpis aliquet. Sed eu orci risus. Suspendisse suscipit arcu mauris, ut iaculis tellus dictum et. Morbi eu aliquet leo, quis scelerisque eros. Proin tristique mi velit, ac lacinia diam pharetra in. Mauris ac enim varius, pellentesque diam et, pharetra ante. Donec felis felis, ultricies id ante eu, finibus lobortis ligula. Ut eget porta justo. Fusce venenatis, mi eget maximus interdum, turpis tellus lacinia nulla, et efficitur ipsum quam et sapien. Vivamus eu luctus augue.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sodales libero enim, eget luctus elit lacinia ullamcorper. Quisque at auctor tortor, nec pharetra leo. Vestibulum a enim a augue scelerisque venenatis cursus quis dui. Praesent accumsan ex sed mi rhoncus tincidunt. Suspendisse lacinia cursus nulla ac ultricies. Nulla pulvinar eget ipsum id consequat. Integer auctor facilisis leo a interdum. Sed a justo scelerisque, mollis quam non, pulvinar leo. Nunc a ante a lectus finibus porta ac ac velit. Etiam ornare nec libero quis pretium. Nulla auctor in dui in condimentum. Nam imperdiet felis molestie risus vehicula, eget ullamcorper turpis dignissim. Mauris eu urna metus.
                <img className="wd-float-left"
                    src="https://www.staradvertiser.com/wp-content/uploads/2021/08/web1_Starship-gap2.jpg" />
                Donec id vehicula libero, sed blandit dui. Pellentesque ex massa, suscipit vitae turpis quis, scelerisque elementum felis. Ut venenatis velit eu ipsum suscipit, nec vestibulum elit tempor. Vestibulum ut cursus sem. Sed molestie nunc eu lobortis eleifend. Mauris dignissim mi sed diam mollis, ac facilisis turpis aliquet. Sed eu orci risus. Suspendisse suscipit arcu mauris, ut iaculis tellus dictum et. Morbi eu aliquet leo, quis scelerisque eros. Proin tristique mi velit, ac lacinia diam pharetra in. Mauris ac enim varius, pellentesque diam et, pharetra ante. Donec felis felis, ultricies id ante eu, finibus lobortis ligula. Ut eget porta justo. Fusce venenatis, mi eget maximus interdum, turpis tellus lacinia nulla, et efficitur ipsum quam et sapien. Vivamus eu luctus augue.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sodales libero enim, eget luctus elit lacinia ullamcorper. Quisque at auctor tortor, nec pharetra leo. Vestibulum a enim a augue scelerisque venenatis cursus quis dui. Praesent accumsan ex sed mi rhoncus tincidunt. Suspendisse lacinia cursus nulla ac ultricies. Nulla pulvinar eget ipsum id consequat. Integer auctor facilisis leo a interdum. Sed a justo scelerisque, mollis quam non, pulvinar leo. Nunc a ante a lectus finibus porta ac ac velit. Etiam ornare nec libero quis pretium. Nulla auctor in dui in condimentum. Nam imperdiet felis molestie risus vehicula, eget ullamcorper turpis dignissim. Mauris eu urna metus.
                <div className="wd-float-done"></div>
            </div>
        </div>

    );
}
